# Author: Kazi Tanvir Azad

spring:
  application:
    name: ${NAME:daily expenses recorder}
  profiles:
    active: ${ACTIVE_PROFILE:local}

server:
  port: ${PORT:8990}
  servlet:
    context-path: /expenses

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,info,beans
